# @url = http://workoutreport.ga:10201/api/
@url = http://localhost:10201/api
@json=Content-Type: application/json

### 
get {{url}}/get-history

### 
get {{url}}/profile
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2JlY2VmMDQ4N2ZjYzZkOWM3YjI4ZiIsImlhdCI6MTY2OTA3MjExNSwiZXhwIjoxNjY5MDcyMTM1fQ.lI-bNehhJjaMM6T05yOuDFuPTYeUwWbrugeQNqZA_Rc

###
post {{url}}/login
{{json}}

{
    "username": "enxing2",
    "password": "1234"
}

###
post {{url}}/register
{{json}}

{
    "username": "enxing4",
    "password": "1234"
}


###
get {{url}}/users

